# Malay Keshav, Rahul Upadhyaya and Khushal Sagar

BLOCK_SIZE = 16384
MAX_REQUEST_TO_PEER = 5 
MAX_TOTAL_REQUESTS = 100
TIMEOUT = 100
GLOBAL_TIMEOUT = 1000
MALI_LIMIT = 1
DIVISION_BLOCK_NUMBER = 20
INITIAL_REQUEST_NUMBER = 2
